<?php 
$_helper = Mage::helper('mgt_developertoolbar');
$_profiler = $this->getProfiler();
$_queries = $_profiler->getQueryProfiles();
?>
<?php if ($_queries): ?>
<table border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td>
      <strong><?php echo $this->__('Executed:'); ?></strong>
    </td>
    <td>
      <?php echo sprintf('%s queries in %s seconds', $_profiler->getTotalNumQueries(), $_profiler->getTotalElapsedSecs()); ?>  
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Average query length:'); ?></strong>
    </td>
    <td>
      <?php echo sprintf('%s seconds', $_profiler->getTotalNumQueries() &&  $_profiler->getTotalElapsedSecs() ? $_profiler->getTotalElapsedSecs()/$_profiler->getTotalNumQueries() : 0); ?>  
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Queries per second:'); ?></strong>
    </td>
    <td>
      <?php echo ($_profiler->getTotalNumQueries() && $_profiler->getTotalElapsedSecs() ?  $_profiler->getTotalNumQueries()/$_profiler->getTotalElapsedSecs() : 0); ?>  
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Longest query length:'); ?></strong>
    </td>
    <td>
      <?php echo $this->getLongestQueryTime(); ?>  
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Longest query:'); ?></strong>
    </td>
    <td>
      <?php echo $_helper->formatSql(wordwrap($this->getLongestQuery())); ?>  
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Total queries:'); ?></strong>
    </td>
    <td>
      <?php echo $this->getProfiler()->getTotalNumQueries(); ?>  
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Insert queries:'); ?></strong>
    </td>
    <td>
      <?php echo $this->getProfiler()->getTotalNumQueries(Zend_Db_Profiler::INSERT); ?>  
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Update queries:'); ?></strong>
    </td>
    <td>
      <?php echo $this->getProfiler()->getTotalNumQueries(Zend_Db_Profiler::UPDATE); ?>  
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Read queries:'); ?></strong>
    </td>
    <td>
      <?php echo $this->getProfiler()->getTotalNumQueries(Zend_Db_Profiler::SELECT); ?>  
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Delete queries:'); ?></strong>
    </td>
    <td>
      <?php echo $this->getProfiler()->getTotalNumQueries(Zend_Db_Profiler::DELETE); ?>  
    </td>
  </tr>
  <tr>
    <td>
      <strong><?php echo $this->__('Transactions:'); ?></strong>
    </td>
    <td>
      <?php echo $this->getProfiler()->getTotalNumQueries(Zend_Db_Profiler::TRANSACTION); ?>  
    </td>
  </tr>
</table>

<ol>
    
  
 <div class="hideshowall"><span class="hideall">hide</span>/<span class="showall">show</span></div>
<?php 
  $profileHelper = Mage::helper('mymod/profiler');
  $i = 0;
  foreach ($_queries as $query): ?>
 
    <li class="<?php echo ($i % 2 ? 'even' : 'odd')?>">
      <?php echo $_helper->formatSql(wordwrap($query->getQuery())); ?>
      <span class="mgt-developer-toolbar-query-info">
      <?php echo $this->__('Elapsed seconds:'); ?> <?php echo $query->getElapsedSecs() ?>
      </span>
    </li>
    <div class="<?php echo ($i % 2 ? 'even' : 'odd')?>">
        
      <?php $arrParams = $query->getQueryParams(); ?>
        <?php if ($arrParams):?>
        <div class ="bold">bind</div>
        <?php endif;?>
 <?php foreach ($arrParams as $key => $value): ?>
        
     <?php if ($key === (string)$key or $value !=false): ?>
    <?php echo'KEY:  <b>  '. $key.' </b>          VALUE:  <b>  '.$value.'</b></br>'; ?>
         <?php  endif ?>
    
 <?php endforeach ?>  
        
        <hr>
        <div class ="hideshow bold" >stack</div> 
 <div class ="stack">
  <?php $stackArr = $profileHelper->getStack($i); ;?>
   <?php foreach ($stackArr as $call): ?>
     <?php if (count($call) === 6): ?>
<?php  echo $call['class']; echo '::'; echo $call['function']?>
     <?php endif ?>
<br/>
<?php endforeach ?>
 </div>
 
        <hr> 
    <p class="hideshow bold">show result</p>    
      <span class="result">
      <?php var_dump($profileHelper->getResult($i));?>
      </span>
    </div>
    <?php $i++; ?>
  <?php endforeach ?>
</ol>
<?php  endif ?>